### ISSUE TITLE
UninstallWidgets.ps1

### ISSUE THREAD

**Issue by undefine-man** [asheroto/UninstallTeams#4]
I used UninstallTeams and UninstallOneDriver , all works really well, and i am appreciate your scripts.

A lot of people don't need windows with fancy functions like Microsoft Teams, OneDriver also Widget.
It is possible to remove embedded Widget using a script like UninstallTeams.ps1 ?
It would benefit a lot of people to make Windows cleaner.

**Comment by asheroto** [comment]
Hi,

Glad you found my scripts useful!

> It is possible to remove embedded Widget using a script like UninstallTeams.ps1 ?

I'm sorry I don't understand what your question is?

**Comment by undefine-man** [comment]
![image](https://github.com/asheroto/UninstallTeams/assets/24623544/99088eb9-f37e-4b83-a6cb-f7126930d9d9)
I mean whether it is possible to remove 'widget' component as easy as removing Teams using a script ?

**Comment by asheroto** [comment]
Oh I see. Did you try `-DisableChatWidget` like here:

![image](https://github.com/asheroto/UninstallTeams/assets/49938263/902e6cc3-0b92-44e9-b0ba-20d08a115598)

https://github.com/asheroto/UninstallTeams?tab=readme-ov-file#parameters

**Comment by asheroto** [comment]
If you click "Chat" it may re-install, I don't know of a way to disable that. If you find a way I can try to implement it though.

**Comment by undefine-man** [comment]
Thanks reply !
I want to remove both Microsoft Teams and Widgets board , i use your script "UninstallTeams.ps1" completely removed Microsoft Teams yesterday and trying to find some way to remove Widgets board too.
This is what i said Widgets
![image](https://github.com/asheroto/UninstallTeams/assets/24623544/73e4e726-92c9-44e5-bb23-4ac45c89d356)

now i successfully removed Widgets board with command :
winget uninstall “windows web experience pack”

Now it looks like this:
![image](https://github.com/asheroto/UninstallTeams/assets/24623544/d75bea7d-58b8-4b96-ba91-742ffc858eba)
compare with before:
![image](https://github.com/asheroto/UninstallTeams/assets/24623544/43c6fc6f-a6d8-4f31-9a10-44f64edde94a)

Really Thanks !

**Comment by asheroto** [comment]
Happy to help!

I see chat is gone but the web experience pack is not just for Teams, so that is probably not something that can removed through this script.
