### ISSUE TITLE
Remove Teams from other user contexts

### ISSUE THREAD

**Issue by stephannn** [asheroto/UninstallTeams#6]
Hi,
we had the issue that we could not remove the appx because it was installed also in another user context. What we did is, we used the PS Application Toolkit to also run the uninstaller in the different user contexts. Anyways, terrible MS setup design.

**Comment by asheroto** [comment]
Interesting. The UninstallTeams script should work for most use cases, but I suppose if specific users had installed it themselves for their account, it may not handle that.

I know we can remove files without a password, but I don't think we can run a program as a user without knowing their credentials. How did you handle this?

**Comment by stephannn** [comment]
We tried it like that with the https://psappdeploytoolkit.com. The _Execute-ProcessAsUser_ function creates a scheduled task under the users session:

```
		Write-Log -Message  "Remove Appx User: Microsoft Teams"
		Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters "-Command `"& {&'Get-AppxPackage' -Name '*MSTeams*' | Remove-AppxPackage -Verbose}`"" -Wait
		
		Write-Log -Message  "Calling Microsoft Teams bootstrapper Uninstaller"
		Execute-Process -Path "$dirFiles\teamsbootstrapper.exe" -Parameters "-x" 
		
		Write-Log -Message  "Remove-MSIApplications - Microsoft Teams Meeting Add-in for Microsoft Office"
		$TeamsOfficeAddin = ((Get-InstalledApplication -Name 'Microsoft Teams Meeting Add-in for Microsoft Office').UninstallSubkey -split '" ').Trim('"')
		if($TeamsOfficeAddin){
			Write-Log -Message  "Remove-MSIApplications User - Microsoft Teams Meeting Add-in for Microsoft Office"
			Execute-ProcessAsUser -Path "C:\Windows\System32\MsiExec.exe" -Parameters "/x $TeamsOfficeAddin /qn"
		}
```

But this is also not the solution and as I said, the problem is more on MS site in my opinion. I think I also have seen their own sub site to uninstall teams, just cannot find it right now.

**Comment by asheroto** [comment]
Ah, I see.

This script is primarily designed for machine-wide deployment, since that's the general deployment type, so individual user installations fall outside its intended scope.

I'll close this issue for now, but if Microsoft introduces a more straight-forward method for per-user uninstallation, we can revisit the possibility of adding that functionality.
